apiVersion: v1
kind: Namespace
metadata:
  name: application-shopmates

--- # Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopmates-api
  namespace: application-shopmates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopmates-api
  template:
    metadata:
      labels:
        app: shopmates-api
    spec:
      containers:
        - name: web-api
          image: axyres/shopmates-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

---
apiVersion: v1
kind: Service
metadata:
  name: shopmates-api-service
  namespace: application-shopmates
spec:
  selector: 
    app: shopmates-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shopmates-api
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]


